### ISSUE TITLE
build does not find add_custom_signals.pxd from cysignals

### ISSUE THREAD

**Issue by videlec** [sagemath/cypari2#125]
```
$ python setup.py build_ext --inplace
running build_ext
Compiling cypari2/custom_block.pyx because it changed.
Compiling cypari2/gen.pyx because it changed.
Compiling cypari2/handle_error.pyx because it changed.
Compiling cypari2/pari_instance.pyx because it changed.
Compiling cypari2/stack.pyx because it depends on ./cypari2/auto_paridecl.pxd.
[1/5] Cythonizing cypari2/custom_block.pyx

Error compiling Cython file:
------------------------------------------------------------
...
#  as published by the Free Software Foundation; either version 2 of
#  the License, or (at your option) any later version.
#                  http://www.gnu.org/licenses/
#*****************************************************************************

from cysignals.signals cimport add_custom_signals
^
------------------------------------------------------------

cypari2/custom_block.pyx:10:0: 'cysignals/signals/add_custom_signals.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
cdef void custom_set_pending_signal(int sig):
    global PARI_SIGINT_pending
    PARI_SIGINT_pending = sig

def init_custom_block():
    add_custom_signals(&custom_signal_is_blocked,
   ^
------------------------------------------------------------

cypari2/custom_block.pyx:27:4: 'add_custom_signals' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
...
cdef void custom_set_pending_signal(int sig):
    global PARI_SIGINT_pending
    PARI_SIGINT_pending = sig

def init_custom_block():
    add_custom_signals(&custom_signal_is_blocked,
                      ^
------------------------------------------------------------

cypari2/custom_block.pyx:27:23: Cannot convert 'int (*)(void)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
    global PARI_SIGINT_pending
    PARI_SIGINT_pending = sig

def init_custom_block():
    add_custom_signals(&custom_signal_is_blocked,
                       &custom_signal_unblock,
                      ^
------------------------------------------------------------

cypari2/custom_block.pyx:28:23: Cannot convert 'void (*)(void)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
    PARI_SIGINT_pending = sig

def init_custom_block():
    add_custom_signals(&custom_signal_is_blocked,
                       &custom_signal_unblock,
                       &custom_set_pending_signal)
                      ^
------------------------------------------------------------

cypari2/custom_block.pyx:29:23: Cannot convert 'void (*)(int)' to Python object
Traceback (most recent call last):
  File "/opt/cypari2/setup.py", line 66, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/opt/cypari2/setup.py", line 46, in run
    self.distribution.ext_modules[:] = cythonize(
  File "/usr/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cypari2/custom_block.pyx
```

**Comment by videlec** [comment]
there were left over files in my environment

**Comment by videlec** [comment]
This is because #117 was merged in master
