### ISSUE TITLE
Compilation issue in handle_error

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/cypari2#145]
`pip install` yields:
```
[4/7] Cythonizing cypari2/handle_error.pyx
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          >>> pari('warning("test")')
          """
          global cb_pari_err_handle
          global cb_pari_err_recover
          cb_pari_err_handle = _pari_err_handle
          cb_pari_err_recover = _pari_err_recover
                                ^
      ------------------------------------------------------------
      
      cypari2/handle_error.pyx:152:26: Cannot assign type 'void (long) except *' to 'void (*)(long) noexcept'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (long) except *'.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-uswtl1p0/cypari2_93ff5e2f312f4f478aa26bb264d56e26/setup.py", line 66, in <module>
          setup(
        File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-uswtl1p0/cypari2_93ff5e2f312f4f478aa26bb264d56e26/setup.py", line 46, in run
          self.distribution.ext_modules[:] = cythonize(
                                             ^^^^^^^^^^
        File "/usr/local/lib64/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/usr/local/lib64/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: cypari2/handle_error.pyx
      [end of output]
```
see eg https://github.com/sagemath/sage/actions/runs/7553246119/job/20563689562

Happens on a few systems.

**Comment by tobiasdiez** [comment]
Seems to be fixed in the (unreleased) new version.
